# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/browser.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 381)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab = QtWidgets.QWidget()
        self.Tab.setObjectName("Tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_bckwrd = QtWidgets.QToolButton(self.Tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_bckwrd.setIcon(icon)
        self.btn_bckwrd.setObjectName("btn_bckwrd")
        self.horizontalLayout.addWidget(self.btn_bckwrd)
        self.btn_reload = QtWidgets.QToolButton(self.Tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reload.setIcon(icon1)
        self.btn_reload.setObjectName("btn_reload")
        self.horizontalLayout.addWidget(self.btn_reload)
        self.btn_frwrd = QtWidgets.QToolButton(self.Tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_frwrd.setIcon(icon2)
        self.btn_frwrd.setObjectName("btn_frwrd")
        self.horizontalLayout.addWidget(self.btn_frwrd)
        self.btn_homepg = QtWidgets.QToolButton(self.Tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_homepg.setIcon(icon3)
        self.btn_homepg.setObjectName("btn_homepg")
        self.horizontalLayout.addWidget(self.btn_homepg)
        self.le_urlAddress = QtWidgets.QLineEdit(self.Tab)
        self.le_urlAddress.setObjectName("le_urlAddress")
        self.horizontalLayout.addWidget(self.le_urlAddress)
        self.btn_search = QtWidgets.QToolButton(self.Tab)
        self.btn_search.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon4)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.Tab)
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.verticalLayout_2.addWidget(self.webEngineView)
        self.tabWidget.addTab(self.Tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_bckwrd_2 = QtWidgets.QToolButton(self.tab_2)
        self.btn_bckwrd_2.setIcon(icon)
        self.btn_bckwrd_2.setObjectName("btn_bckwrd_2")
        self.horizontalLayout_2.addWidget(self.btn_bckwrd_2)
        self.btn_reload_2 = QtWidgets.QToolButton(self.tab_2)
        self.btn_reload_2.setIcon(icon1)
        self.btn_reload_2.setObjectName("btn_reload_2")
        self.horizontalLayout_2.addWidget(self.btn_reload_2)
        self.btn_frwrd_2 = QtWidgets.QToolButton(self.tab_2)
        self.btn_frwrd_2.setIcon(icon2)
        self.btn_frwrd_2.setObjectName("btn_frwrd_2")
        self.horizontalLayout_2.addWidget(self.btn_frwrd_2)
        self.btn_homepg_2 = QtWidgets.QToolButton(self.tab_2)
        self.btn_homepg_2.setIcon(icon3)
        self.btn_homepg_2.setObjectName("btn_homepg_2")
        self.horizontalLayout_2.addWidget(self.btn_homepg_2)
        self.le_urlAddress_2 = QtWidgets.QLineEdit(self.tab_2)
        self.le_urlAddress_2.setObjectName("le_urlAddress_2")
        self.horizontalLayout_2.addWidget(self.le_urlAddress_2)
        self.btn_search_2 = QtWidgets.QToolButton(self.tab_2)
        self.btn_search_2.setText("")
        self.btn_search_2.setIcon(icon4)
        self.btn_search_2.setObjectName("btn_search_2")
        self.horizontalLayout_2.addWidget(self.btn_search_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.webEngineView_2 = QtWebEngineWidgets.QWebEngineView(self.tab_2)
        self.webEngineView_2.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_2.setObjectName("webEngineView_2")
        self.verticalLayout_3.addWidget(self.webEngineView_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 676, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuWindow = QtWidgets.QMenu(self.menuBar)
        self.menuWindow.setObjectName("menuWindow")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave_File = QtWidgets.QAction(MainWindow)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionGo_to_Page = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Page.setObjectName("actionGo_to_Page")
        self.actionGo_to_Home = QtWidgets.QAction(MainWindow)
        self.actionGo_to_Home.setObjectName("actionGo_to_Home")
        self.actionReload = QtWidgets.QAction(MainWindow)
        self.actionReload.setObjectName("actionReload")
        self.actionGo_Back = QtWidgets.QAction(MainWindow)
        self.actionGo_Back.setObjectName("actionGo_Back")
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")
        self.actionNew_Tab = QtWidgets.QAction(MainWindow)
        self.actionNew_Tab.setObjectName("actionNew_Tab")
        self.actionClose_Tab = QtWidgets.QAction(MainWindow)
        self.actionClose_Tab.setObjectName("actionClose_Tab")
        self.actionSwitch_Tabs = QtWidgets.QAction(MainWindow)
        self.actionSwitch_Tabs.setObjectName("actionSwitch_Tabs")
        self.actionNew_Window_2 = QtWidgets.QAction(MainWindow)
        self.actionNew_Window_2.setObjectName("actionNew_Window_2")
        self.actionClose_Window = QtWidgets.QAction(MainWindow)
        self.actionClose_Window.setObjectName("actionClose_Window")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew_Tab)
        self.menuFile.addAction(self.actionClose_Tab)
        self.menuFile.addAction(self.actionSwitch_Tabs)
        self.menuView.addAction(self.actionGo_to_Page)
        self.menuView.addAction(self.actionGo_to_Home)
        self.menuView.addAction(self.actionGo_Back)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionReload)
        self.menuWindow.addAction(self.actionNew_Window_2)
        self.menuWindow.addAction(self.actionClose_Window)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.btn_reload.clicked.connect(self.webEngineView.reload)
        self.btn_bckwrd.clicked.connect(self.webEngineView.back)
        self.btn_frwrd.clicked.connect(self.webEngineView.forward)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.btn_bckwrd)
        MainWindow.setTabOrder(self.btn_bckwrd, self.btn_reload)
        MainWindow.setTabOrder(self.btn_reload, self.btn_frwrd)
        MainWindow.setTabOrder(self.btn_frwrd, self.btn_homepg)
        MainWindow.setTabOrder(self.btn_homepg, self.le_urlAddress)
        MainWindow.setTabOrder(self.le_urlAddress, self.btn_search)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_bckwrd.setText(_translate("MainWindow", "..."))
        self.btn_reload.setText(_translate("MainWindow", "..."))
        self.btn_frwrd.setText(_translate("MainWindow", "..."))
        self.btn_homepg.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab), _translate("MainWindow", "New Tab"))
        self.btn_bckwrd_2.setText(_translate("MainWindow", "..."))
        self.btn_reload_2.setText(_translate("MainWindow", "..."))
        self.btn_frwrd_2.setText(_translate("MainWindow", "..."))
        self.btn_homepg_2.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "New Tab"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_File.setText(_translate("MainWindow", "Save File"))
        self.actionSave_File.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionGo_to_Page.setText(_translate("MainWindow", "Go to Page"))
        self.actionGo_to_Page.setShortcut(_translate("MainWindow", "Return"))
        self.actionGo_to_Home.setText(_translate("MainWindow", "Go to Home"))
        self.actionGo_to_Home.setShortcut(_translate("MainWindow", "Shift+Backspace"))
        self.actionReload.setText(_translate("MainWindow", "Reload"))
        self.actionReload.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionGo_Back.setText(_translate("MainWindow", "Go Back"))
        self.actionGo_Back.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.actionNew_Window.setText(_translate("MainWindow", "New Window"))
        self.actionNew_Tab.setText(_translate("MainWindow", "New Tab"))
        self.actionClose_Tab.setText(_translate("MainWindow", "Close Tab"))
        self.actionSwitch_Tabs.setText(_translate("MainWindow", "Switch Tabs"))
        self.actionNew_Window_2.setText(_translate("MainWindow", "New Window"))
        self.actionClose_Window.setText(_translate("MainWindow", "Close Window"))
from PyQt5 import QtWebEngineWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
